# Generated by Django 4.1.4 on 2023-01-20 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=30)),
                ('empno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('EID', models.IntegerField(primary_key=True, serialize=False)),
                ('MGR', models.IntegerField()),
                ('ENAME', models.CharField(max_length=50)),
                ('sal', models.FloatField()),
                ('hiredate', models.DateField()),
                ('position', models.CharField(max_length=50)),
                ('deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
